--OBTER O NOME DOS CLIENTES QUE NÃO FORAM ATENDIDOS PELO VENDEDOR ROBERTO:
SELECT NOME FROM CLIENTE WHERE COD_CLI NOT IN
(SELECT COD_CLI FROM VENDA WHERE COD_VEND IN
(SELECT COD_VEND FROM VENDEDOR WHERE NOME='ROBERTO'));
--OBTER O NOME DOS PRODUTOS MAIS COMPRADOS NO MÊS DE JANEIRO DE 2023:
SELECT NOME FROM PRODUTO WHERE COD_PROD IN
(SELECT COD_PROD FROM ITEM_VENDA WHERE QUANT_VEN IN
(SELECT MAX(QUANT_VEN) FROM ITEM_VENDA WHERE COD_VEN IN
(SELECT COD_VEN FROM VENDA WHERE DT_VEND>='2023-01-01' AND DT_VEND<='2023-01-31')));
--OBTER O NOME DO FORNECEDOR QUE MAIS VENDEU PRODUTOS:
SELECT NOME FROM FORNECEDOR WHERE COD_FORN IN
(SELECT MAX(COD_FORN) FROM COMPRA);
--REAJUSTAR O VALOR DO VALOR TOTAL DOS ITENS COMPRADOS COM DESCONTO DE 5%:
UPDATE ITEM_COMPRA SET VALOR_TOTAL = VALOR_TOTAL * 0.95;
--OBTER O NOME DOS CLIENTES QUE NÃO COMPRARAM NENHUM PRODUTO:
SELECT NOME FROM CLIENTE WHERE COD_CLI NOT IN
(SELECT COD_CLI FROM VENDA);
--OBTER O NOME DOS CLIENTES QUE MAIS GASTOU EM UNICA COMPRA:
SELECT NOME FROM CLIENTE WHERE COD_CLI IN
(SELECT COD_CLI FROM VENDA WHERE COD_VEN IN
(SELECT COD_VEN FROM ITEM_VENDA WHERE VALOR_TOTAL IN
(SELECT MAX(VALOR_TOTAL) FROM ITEM_VENDA)));

SELECT NOME FROM PRODUTO WHERE COD_PROD IN
    (SELECT MAX(COD_PROD) FROM item_venda WHERE COD_VEN IN
     (SELECT COD_VEN FROM VENDA WHERE DT_VEND >= '2023-01-01' AND DT_VEND <= '2023-01-31'));